language: go
go:
  - 1.13.6

services:
  - docker

before_install:
- docker pull centos
- docker run  centos /bin/sh -c "yum install -y go make git; cd /home; git clone https://github.com/ontio/ontology -b v1.10.0; cd ontology; make ontology; ./ontology --version;"

