language: go

go_import_path: github.com/ontio/ontology

install:
  - go get github.com/Masterminds/glide
  - glide install

go:
  - 1.10.x

script:
  - make
  - bash ./.travis.gofmt.sh
  - bash ./.travis.gotest.sh
